In [1]:
import warnings
warnings.filterwarnings('ignore')
import torch
from torch_geometric.loader import DataLoader
from src.training.train import train
from src.model.gae import GAE
from src.data.loader import GraphDataset
from src.utils import commons
torch.cuda.empty_cache()

config = commons.get_config('configs/default.yaml')
device = commons.get_device()
# device = 'cuda'
dataset = GraphDataset()
model = GAE(config=config['model']).to(device)

train_loader = DataLoader(dataset=dataset, 
                          batch_size=config['training']['batch_size'], 
                          shuffle=False,
                          num_workers=config['training']['num_workers'])

train_history = train(model=model, 
                      device=device,
                      train_loader=train_loader, 
                      config=config['training'])

  0%|          | 0/100 [00:00<?, ?it/s]

: 

In [1]:
from src.utils.commons import get_config, get_device
from src.model.gae import GAE
from src.data.loader import GraphDataset
from warnings import filterwarnings
filterwarnings('ignore')

config = get_config('configs/default.yaml')
device = get_device()
dataset = GraphDataset()
model = GAE(config=config['model']).to(device)

In [2]:
from torch_geometric.loader import DataLoader
from src.training.train import train

train_loader = DataLoader(dataset=dataset, 
                          batch_size=config['training']['batch_size'], 
                          shuffle=False,
                          num_workers=config['training']['num_workers'])

train_history = train(model=model, 
                      device=device,
                      train_loader=train_loader,
                      print_every=10,
                      single_batch=True,
                      config=config['training'])

 22%|██▏       | 11/50 [16:19<57:24, 88.32s/it]  

Epoch 11/50, Loss: 36.95124053955078


 42%|████▏     | 21/50 [30:36<41:47, 86.48s/it]

Epoch 21/50, Loss: 36.52711486816406


 62%|██████▏   | 31/50 [44:53<26:53, 84.90s/it]

Epoch 31/50, Loss: 36.78425979614258


 82%|████████▏ | 41/50 [58:49<12:33, 83.69s/it]

Epoch 41/50, Loss: 36.77402877807617


100%|██████████| 50/50 [1:11:26<00:00, 85.73s/it]


<generator object Module.parameters at 0x0000018ED6330C10>

In [ ]:
batch.x, latent_variables = model(batch)

TopKPooling

In [8]:
from torch_geometric.nn.pool import topk_unpool

ImportError: cannot import name 'topk_unpool' from 'torch_geometric.nn.pool' (c:\Users\Yuno\anaconda3\envs\'gca_rom'\lib\site-packages\torch_geometric\nn\pool\__init__.py)

In [2]:
from torch_geometric.nn.pool import TopKPooling
from src.data.loader import GraphDataset
import torch.nn as nn
# Create dataset and 
dataset = GraphDataset()
batch = dataset[0]
topk = TopKPooling(in_channels=2, ratio=0.5, nonlinearity='relu')

d:\TA\TA2\GAE-ROM\src\data\loader.py:47: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  edge_index = torch.tensor(self.edge_list, dtype=torch.long),
d:\TA\TA2\GAE-ROM\src\data\loader.py:48: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  edge_attr = torch.tensor(self.edge_features, dtype=torch.float32),
d:\TA\TA2\GAE-ROM\src\data\loader.py:49: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  edge_weight = torch.tensor(self.edge_weights, dtype=torch.float32))


In [3]:
print(batch.x.shape)
print(batch.edge_index.shape)
print(batch.edge_attr.shape)
pooled_x, pooled_edge_index, pooled_edge_attr, batch_index, perm, score = topk(x = batch.x, edge_index = batch.edge_index, edge_attr = batch.edge_attr)

print(pooled_x.shape)
print(pooled_edge_index.shape)
print(pooled_edge_attr.shape)
print(batch_index.shape)
print(perm.shape)
print(score.shape)

torch.Size([30846, 2])
torch.Size([2, 46015])
torch.Size([46015])
torch.Size([15423, 2])
torch.Size([2, 22705])
torch.Size([22705])
torch.Size([15423])
torch.Size([15423])
torch.Size([15423])


In [4]:
batch_index

tensor([0, 0, 0,  ..., 0, 0, 0])

In [9]:
import torch

def topk_unpool(x_pooled, perm, num_nodes):
    x_unpooled = torch.zeros(num_nodes, x_pooled.size(1), device=x_pooled.device)
    x_unpooled[perm] = x_pooled
    return x_unpooled

unpooled_x = topk_unpool(pooled_x, perm, num_nodes = batch.num_nodes)


In [11]:
perm

tensor([20468,  7050,    88,  ..., 15420, 15421, 15422])

In [10]:
unpooled_x.shape

torch.Size([30846, 2])

In [1]:
pooled_x.shape

NameError: name 'pooled_x' is not defined

EdgePooling

In [1]:
from torch_geometric.nn.pool import EdgePooling
from torch_geometric.nn import GCNConv, ChebConv, GATConv, GMMConv
from src.data.loader import GraphDataset
import torch.nn as nn
# Create dataset and get a batch
dataset = GraphDataset()
batch = dataset[0]
edgepool = EdgePooling(in_channels=2, dropout=0)

d:\TA\TA2\GAE-ROM\src\data\loader.py:47: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  edge_index = torch.tensor(self.edge_list, dtype=torch.long),
d:\TA\TA2\GAE-ROM\src\data\loader.py:48: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  edge_attr = torch.tensor(self.edge_features, dtype=torch.float32),
d:\TA\TA2\GAE-ROM\src\data\loader.py:49: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  edge_weight = torch.tensor(self.edge_weights, dtype=torch.float32))


In [9]:
batch.pos

tensor([[2.5045, 2.8414],
        [4.1457, 2.4405],
        [2.9354, 1.7456],
        ...,
        [2.3839, 1.3395],
        [1.0981, 1.1352],
        [1.5320, 1.6905]])

In [12]:
print(type(batch))           # should be <class 'torch_geometric.data.data.Data'>
print(type(batch.batch))     # should be <class 'torch.Tensor'>
print(batch.x.size(0))     # e.g., [num_nodes]


<class 'torch_geometric.data.data.Data'>
<class 'NoneType'>
30846


In [7]:
print(batch.x.shape)
print(batch.edge_index.shape)
print(max(batch.edge_index[1]))
print(batch.edge_attr.shape)
import torch

# If your graph has N nodes, all belong to the same graph, so assign zeros:
batch_vector = torch.zeros(batch.x.size(0), dtype=torch.long)

pooled_x, pooled_edge_index, pooled_batch, unpool_info = edgepool(batch =  batch_vector, x = batch.x, edge_index = batch.edge_index)
# pooled_result = edgepool(batch = batch_vector, x = batch.x, edge_index = batch.edge_index)

print(pooled_x.shape)
print(pooled_edge_index.shape)
print(max(pooled_edge_index[1]))
print(pooled_batch)

torch.Size([30846, 2])
torch.Size([2, 46015])
tensor(30845)
torch.Size([46015])
torch.Size([17306, 2])
torch.Size([2, 46014])
tensor(17305)
tensor([0, 0, 0,  ..., 0, 0, 0])


In [16]:
batch.x

tensor([[46.3758, -0.8608],
        [38.7250, -1.5845],
        [40.6678, -1.4719],
        ...,
        [28.8896, -2.3286],
        [34.1928, -0.3318],
        [34.1816, -0.2373]])

In [15]:
pooled_x

tensor([[ 1.0998e+02,  8.1582e-01],
        [ 1.3889e+02, -2.8769e+00],
        [ 1.1589e+02, -4.7028e+00],
        ...,
        [ 3.5362e+01, -6.6867e-02],
        [ 3.5490e+01,  7.5209e-01],
        [ 3.5759e+01,  1.4351e+00]], grad_fn=<MulBackward0>)

In [ ]:
from src.utils.plot import Plot

plot = Plot(data_dir = "data", save_dir = "output")
plot.plot_tensor(tensor = pooled_x[:,0], data_dim = (1, 2), title = "Pooled X")
